export const COLOR_GRAY = "#dedede"
export const COLOR_HEADLINE = "#4e6778"
export const FONT_FAMILY_SERIF = "'Roboto Slab', serif"
export const FONT_FAMILY_SANS_SERIF = "'Open Sans', Arial, sans-serif"
export const FONT_SIZE_LARGE = "18px"
export const FONT_SIZE_NORMAL = "16px"
export const FONT_SIZE_SMALL = "14px"
export const MARGIN_TOP_CONTAINER = "1em"
