# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='Untitled Exam', help_text='Exam Title', max_length=512),
        ),
    ]
